apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  # these labels are replica set labels
  labels:
    component: frontend
    tier: frontend
    project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      component: frontend
      tier: frontend
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        component: frontend
        tier: frontend
        project: roboshop
    spec: 
      containers:
      - name: frontend
        image: joindevops/frontend:v1
        imagePullPolicy: Always
        readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15

---
#service

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    tier: frontend
  ports:
    - protocal: TCP
      port: 80 #service port
      targetPort: 80 #container port
