apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  # these labels are replica set labels
  labels:
  component: frontend
  tier: frontend
  project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLables:
      component: frontend
      tier: frontend
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        component: frontend
        tier: frontend
        project: roboshop
    spec: 
      containers:
      - name: frontend
        image: joindevops/frontend:v1
        imagePullPolicy: Always
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 20
        periodSeconds: 5

---
#service

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    tier: frontend
  ports:
    - protocal: TCP
      port: 80 #service port
      targetPort: 80 #container port
