apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---
apiVersion: v1
kind: Deployment
metadata: 
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    matchLables:
      component: payment
      project: roboshop
      tier: backend
  template:
    metadata:
      labels:
        component: payment
        project: roboshop
        tier: backend
    spec:
      containers:
      - name: payment
        image: joindevops/payment:v1
        imagePullPolicy: Always
        envForm:
          configMapRef:
            name: payment
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 60

        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    component: payment
    project: roboshop
    tier: backend 
  ports:
    - protocal: TCP
      port: 8080 #service port
      targetPort: 8080 #container port
