apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: v1
kind: Deployment
metadata: 
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    matchLables:
      component: cart
      project: roboshop
      tier: backend
  template:
    metadata:
      labels:
        component: cart
        project: roboshop
        tier: backend
    spec:
      containers:
      - name: cart
        image: joindevops/cart:v1
        imagePullPolicy: Always
        envForm:
          configMapRef:
            name: cart
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 60

        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    component: cart
    project: roboshop
    tier: backend 
  ports:
    - protocal: TCP
      port: 8080 #service port
      targetPort: 8080 #container port
