apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  # these labels are replica set labels
  labels:
    component: rabbitmq
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLables:
      component: rabbitmq
      tier: db
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        component: rabbitmq
        tier: db
        project: roboshop
    spec: 
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        imagePullPolicy: Always
        envForm:
        - name: RABBITMQ_DEFAULT_USER
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 10

---
#service

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: frontend
    tier: db
  ports:
    - protocal: TCP
      port: 5672 #service port
      targetPort: 5672 #container port
