apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # these labels are replica set labels
  labels:
  component: mongodb
  tier: db
  project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLables:
      component: mongodb
      tier: db
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        component: mongodb
        tier: db
        project: roboshop
    spec: 
      containers:
      - name: mongodb
        image: joindevops/mongodb:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10

---
#service

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    project: roboshop
    component: frontend
    tier: db
  ports:
    - protocal: TCP
      port: 27017 #service port
      targetPort: 27017 #container port
