apiVersion: v1
kind: ConfigMap
metadata: 
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # these labels are replica set labels
  labels:
  component: mysql
  tier: db
  project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLables:
      component: mysql
      tier: db
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        component: mysql
        tier: db
        project: roboshop
    spec: 
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        imagePullPolicy: Always
        # readinessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
      
      volumes:
      - name: mysql-config 
        configMap:
          name: mysql

---
#service

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: frontend
    tier: db
  ports:
    - protocal: TCP
      port: 3306 #service port
      targetPort: 3306 #container port
