apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: v1
kind: Deployment
metadata: 
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    matchLables:
      component: catalogue
      project: roboshop
      tier: backend
  template:
    metadata:
      labels:
        component: catalogue
        project: roboshop
        tier: backend
    spec:
      containers:
      - name: catalogue
        image: joindevops/catalogue:v1
        imagePullPolicy: always
        envForm:
          configMapRef:
            name: catalogue
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 60

        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 60