apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/user"
  REDIS_URL: "redis://redis:6379"
---
apiVersion: v1
kind: Deployment
metadata: 
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    matchLables:
      component: user
      project: roboshop
      tier: backend
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: backend
    spec:
      containers:
      - name: user
        image: joindevops/user:v1
        imagePullPolicy: Always
        envForm:
          configMapRef:
            name: user
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 60

        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    component: user
    project: roboshop
    tier: backend 
  ports:
    - protocal: TCP
      port: 8080 #service port
      targetPort: 8080 #container port
