apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  # these labels are replica set labels
  labels:
  component: redis
  tier: db
  project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLables:
      component: redis
      tier: db
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        component: redis
        tier: db
        project: roboshop
    spec: 
      containers:
      - name: redis
        image: redis:7.0
        imagePullPolicy: Always
      readinessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 10
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 10
        periodSeconds: 10

---
#service

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: frontend
    tier: db
  ports:
    - protocal: TCP
      port: 6379 #service port
      targetPort: 6379 #container port
